#ifndef MODELS_MESSAGETYPE_HPP_
#define MODELS_MESSAGETYPE_HPP_

namespace VolSync
{

enum class MessageType
{
    INVALID = 0x00,
    REQUEST_ABORT = 0x10,
    RESPONSE_ABORT = 0x11,
    REQUEST_VERSION = 0x12,
    RESPONSE_VERSION = 0x13,
    REQUEST_VOLUME_INFORMATION = 0x14,
    RESPONSE_VOLUME_INFORMATION = 0x15,
    REQUEST_SET_CHUNK_SIZE = 0x16,
    RESPONSE_SET_CHUNK_SIZE = 0x17,
    REQUEST_SET_CHUNK_INDEX = 0x18,
    RESPONSE_SET_CHUNK_INDEX = 0x19,
};

} /* namespace VolSync */

#endif /* MODELS_MESSAGETYPE_HPP_ */
