#ifndef MODELS_MESSAGETYPE_HPP_
#define MODELS_MESSAGETYPE_HPP_

namespace VolSync
{

enum class MessageType
{
    INVALID = 0x00,
    REQUEST_ABORT = 0x10,
    RESPONSE_ABORT = 0x11,
    REQUEST_VERSION = 0x12,
    RESPONSE_VERSION = 0x13,
    REQUEST_VOLUME_INFORMATION = 0x20,
    RESPONSE_VOLUME_INFORMATION = 0x21,
    REQUEST_OPEN_VOLUME = 0x22,
    RESPONSE_OPEN_VOLUME = 0x23,
    REQUEST_CLOSE_VOLUME = 0x24,
    RESPONSE_CLOSE_VOLUME = 0x25,
    REQUEST_SET_CHUNK_SIZE = 0x30,
    RESPONSE_SET_CHUNK_SIZE = 0x31,
    REQUEST_SET_CHUNK_INDEX = 0x32,
    RESPONSE_SET_CHUNK_INDEX = 0x33,
    REQUEST_GET_CHUNK_HASH = 0x34,
    RESPONSE_GET_CHUNK_HASH = 0x35,
    REQUEST_WRITE_CHUNK_TO_TARGET = 0x36,
    RESPONSE_WRITE_CHUNK_TO_TARGET = 0x37,
};

} /* namespace VolSync */

#endif /* MODELS_MESSAGETYPE_HPP_ */
